name: BCC
version: 0.1
author: CharybdeBE
main: be.charybde.bank.BCC
softdepend: [Vault]
commands:
      bank:
               description: Gestion of bank accounts
               usage:  Utilisation  bank [pay|withdraw|list] COMPTE MONTANT
permissions:
    bcc.create:
        description: Allow user to create accounts
        default: false
    bcc.list:
        description: Allow user to see all accounts
        default: false